### ISSUE TITLE
fio_scripts for linux

### ISSUE THREAD

**Issue by kiranfractal** [khailey/fio_scripts#5]
From the code it is using DTrace so how can we use it on Linux machines ?

**Comment by khailey** [comment]
DTrace execution is set by a command line flag "-d", thus on Linux  run the scripts with out the DTrace command line flag

- Kyle

**Comment by kiranfractal** [comment]
Thanks a lot, I will try it and report if there are any issues.

**Comment by kiranfractal** [comment]
The scripts are not usable for normal fio output, I think due to your scripts are parsing some new fields which are not in by default latest fio output.

**Comment by khailey** [comment]
yes, the scripts, as mentioned in the README, are for 2.0.7 of FIO available here
download: http://brick.kernel.dk/snaps/fio-2.0.7.tar.gz

**Comment by kiranfractal** [comment]
That is too old build. Any plans to update for current fio version ?

Thanks.

**Comment by khailey** [comment]
I'm not working on FIO right now, so won't happen right now.
I want to do some more work on it but busy with other things right now.
Cool think about github is it's collaborative so maybe someone wants to adjust the script to the newest version of fio.
Personally, version 2.0.7 runs fine and we are using it heavily at our company.
