### ISSUE TITLE
explanation of fioparse output...

### ISSUE THREAD

**Issue by abdulirfan3** [khailey/fio_scripts#7]
Hi Kyle,

I find these script very useful, I am looking to get some explanation with regards to the fioparse.sh script..

![image](https://cloud.githubusercontent.com/assets/11415069/17379468/4321294e-5988-11e6-8a62-04714805329e.png)

For example in the above screenshot I want to understand what does the column "ms, min, max" mean?  If min, max is in millisecond, then what does the ms column mean ?

Also with regards to the screenshot above(high lighted line), If MAX time it took was 1134 millisecond(1.34 seconds), then why is 95% of the operations falls under "2s" histogram ?

Just trying to understand this output. as i am unable to find any documentation on it.  I suppose I can always look at the script, but I am not so good in perl

**Comment by khailey** [comment]
There are multiple IOs
Min is the fastest
Max is the slowest
95% is the response time that 95% of the IOs finish in

**Comment by abdulirfan3** [comment]
Thank you Kyle.  What about the "ms" column ?? is that the avg ?? if that is the average, can you please help me understand the below(from the high lighted screenshot)

ms(avg?) = 1047.6
min         = 29.0
max         = 1134.0

under histogram 
1s = 4
2s = 95


if my min is 29 ms, shouldn't that be accounted for in the 20ms - 50ms histogram ?? or is that missing due to std ?

**Comment by khailey** [comment]
Ms is average 
A histogram bucket an be empty because the buckets show % not count so if the % is under .5 it won't show up

**Comment by abdulirfan3** [comment]
Thank you Kyle for all that information.
